version: '3.1'
networks:
  tp2-Docker:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  app:
    build:
      tags: ["datchos/tp2-docker"]
      context: .
    restart: unless-stopped
    environment:
     - DB=172.20.0.11
    depends_on:
      - mongo
    networks:
      tp2-Docker:
        ipv4_address:  172.20.0.10
    ports:
      - 5000:5000
  mongo:
    image: "mongo:3.2"
    container_name: mongo
    restart: unless-stopped
    networks:
      tp2-Docker:
        ipv4_address:  172.20.0.11
    ports:
      - 27017:27017
