version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile-apache
    image: datchos/debian-glpi:v1
    ports:
      - '8100:80'
    depends_on:
      - db
  mysql:
    build:
      dockerfile: Dockerfile-mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root_password
       MYSQL_DATABASE: dev
       MYSQL_USER: dev_user
       MYSQL_PASSWORD: dev_password
    ports:
       - 3306:3306
volumes:
  mysqldata: {}
