version: '3.1'
networks:
  tp2-Docker:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  frontend:
    build:
      tags: ["datchos/api-frontend"]
      context: "./api-frontend"
    restart: unless-stopped
    environment:
     - API_BACKEND_URL=172.20.0.11
     - API_BACKEND_PORT=8001
    depends_on:
      - backend
    networks:
      tp2-Docker:
        ipv4_address:  172.20.0.10
    ports:
      - 8000:8000
  backend:
    build:
      tags: ["datchos/api-backend"]
      context: "./api-backend"
    restart: unless-stopped
    networks:
      tp2-Docker:
        ipv4_address:  172.20.0.11
    ports:
      - 8001:8001
