version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-apache
    image: datchos/debian-glpi:v1
    ports:
      - '8100:80'
    depends_on:
      - db
  db:
    image: mysql
    container_name: mydb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: glpi
      MYSQL_DATABASE: glpi
      MYSQL_PASSWORD: glpipassword
    ports:
      - 3306:3306
